// Mock data for development until Supabase is connected
// Bu veriler geliştirme sürecinde kullanılacak, Supabase bağlandığında kaldırılacak

export const mockStoreSettings = {
  id: "default",
  name: "CellBroos",
  logo_url: null,
  logo_text: "CellBroos",
  favicon_url: null,
  address: "Atatürk Cad. No:42, Merkez, İstanbul",
  phone: "+90 212 555 0042",
  whatsapp: "+905551234567",
  working_hours: {
    mon: { open: "09:00", close: "20:00" },
    tue: { open: "09:00", close: "20:00" },
    wed: { open: "09:00", close: "20:00" },
    thu: { open: "09:00", close: "20:00" },
    fri: { open: "09:00", close: "20:00" },
    sat: { open: "10:00", close: "18:00" },
    sun: null,
  },
  map_coordinates: "41.0082,28.9784",
  google_maps_url: "https://maps.google.com/?q=41.0082,28.9784",
  social_links: {
    instagram: "https://instagram.com/cellbroos",
    facebook: "https://facebook.com/cellbroos",
    tiktok: "https://tiktok.com/@cellbroos",
  },
  why_us: [
    {
      title: "Garantili & Faturalı",
      desc: "Tüm ürünlerimiz distribütör garantili, orijinal kutusunda ve adınıza faturalı olarak teslim edilir.",
      icon: "Award"
    },
    {
      title: "Güvenilir Alışveriş",
      desc: "Ürünü mağazamızda fiziki olarak test edin, uzman kadromuz eşliğinde güvenle satın alın.",
      icon: "ShieldCheck"
    },
    {
      title: "Satış Sonrası Destek",
      desc: "Veri transferi, kurulum ve aksesuarlarla ilgili her türlü sorunuzda daima yanınızdayız.",
      icon: "HeartHandshake"
    }
  ],
  brands: ["Apple", "Samsung", "Xiaomi", "Huawei", "OnePlus", "Oppo", "Realme"],
  featured_title: "Öne Çıkan Telefonlar",
  announcement_text: "🔥 Yeni iPhone 16 Pro Max stokta! Hemen mağazamıza gelin.",
  announcement_active: true,
};

export const mockCategories = [
  {
    id: "cat-1",
    name: "iPhone",
    slug: "iphone",
    description: "Apple iPhone serisi",
    image_url: "/products/iphone-16-pro-max.png",
    bg_color: "#f0f4ff",
    display_order: 1,
  },
  {
    id: "cat-2",
    name: "Samsung",
    slug: "samsung",
    description: "Samsung Galaxy serisi",
    image_url: "/products/samsung-galaxy-s25-ultra.png",
    bg_color: "#f5f5f7",
    display_order: 2,
  },
  {
    id: "cat-3",
    name: "Xiaomi",
    slug: "xiaomi",
    description: "Xiaomi telefon serisi",
    image_url: "/products/xiaomi-15-pro.png",
    bg_color: "#fff7ed",
    display_order: 3,
  },
  {
    id: "cat-4",
    name: "Kulaklık",
    slug: "kulaklik",
    description: "Kablosuz kulaklık modelleri",
    image_url: "/categories/headphones.png",
    bg_color: "#f5f5f7",
    display_order: 4,
  },
  {
    id: "cat-5",
    name: "Kılıf & Koruma",
    slug: "kilif",
    description: "Telefon kılıfları ve ekran koruyucular",
    image_url: "/categories/cases.png",
    bg_color: "#f0f7f0",
    display_order: 5,
  },
  {
    id: "cat-6",
    name: "Aksesuar",
    slug: "aksesuar",
    description: "Şarj, kablo ve diğer aksesuarlar",
    image_url: "/categories/accessories.png",
    bg_color: "#fdf2f8",
    display_order: 6,
  },
];

export const mockProducts = [
  // ─── TELEFONLAR ───────────────────────────────────────────────
  {
    id: "prod-1",
    name: "iPhone 16 Pro Max",
    slug: "iphone-16-pro-max",
    description:
      "Apple'ın en güçlü telefonu. A18 Pro çip, 48MP kamera sistemi ve titanium tasarım ile üstün performans.",
    brand: "Apple",
    model: "iPhone 16 Pro Max",
    price: 84999,
    specs: {
      ekran: '6.9" Super Retina XDR OLED',
      islemci: "A18 Pro",
      ram: "8 GB",
      depolama: "256 GB / 512 GB / 1 TB",
      kamera: "48MP + 12MP + 12MP",
      pil: "4685 mAh",
      os: "iOS 18",
    },
    image_url: "/products/iphone-16-pro-max.png",
    images: [],
    stock_status: "IN_STOCK",
    is_featured: true,
    is_active: true,
    display_order: 1,
    meta_title: "iPhone 16 Pro Max | CellBroos",
    meta_description: "iPhone 16 Pro Max en uygun fiyatlarla CellBroos mağazasında.",
    category_id: "cat-1",
    category: { name: "iPhone", slug: "iphone" },
  },
  {
    id: "prod-2",
    name: "Samsung Galaxy S25 Ultra",
    slug: "samsung-galaxy-s25-ultra",
    description:
      "Samsung'un amiral gemisi. Snapdragon 8 Elite, 200MP kamera ve S Pen desteği ile sınırları zorlayın.",
    brand: "Samsung",
    model: "Galaxy S25 Ultra",
    price: 74999,
    specs: {
      ekran: '6.8" Dynamic AMOLED 2X',
      islemci: "Snapdragon 8 Elite",
      ram: "12 GB",
      depolama: "256 GB / 512 GB / 1 TB",
      kamera: "200MP + 50MP + 10MP + 12MP",
      pil: "5000 mAh",
      os: "Android 15 (One UI 7)",
    },
    image_url: "/products/samsung-galaxy-s25-ultra.png",
    images: [],
    stock_status: "IN_STOCK",
    is_featured: true,
    is_active: true,
    display_order: 2,
    meta_title: "Samsung Galaxy S25 Ultra | CellBroos",
    meta_description: "Samsung Galaxy S25 Ultra en uygun fiyatlarla CellBroos mağazasında.",
    category_id: "cat-2",
    category: { name: "Samsung", slug: "samsung" },
  },
  {
    id: "prod-3",
    name: "Xiaomi 15 Pro",
    slug: "xiaomi-15-pro",
    description:
      "Xiaomi'nin en iyi performanslı modeli. Leica optiği, Snapdragon 8 Elite ve ultra hızlı şarj.",
    brand: "Xiaomi",
    model: "15 Pro",
    price: 42999,
    specs: {
      ekran: '6.73" LTPO AMOLED',
      islemci: "Snapdragon 8 Elite",
      ram: "12 GB / 16 GB",
      depolama: "256 GB / 512 GB",
      kamera: "50MP (Leica) + 50MP + 50MP",
      pil: "6100 mAh",
      os: "Android 15 (HyperOS 2)",
    },
    image_url: "/products/xiaomi-15-pro.png",
    images: [],
    stock_status: "IN_STOCK",
    is_featured: true,
    is_active: true,
    display_order: 3,
    meta_title: "Xiaomi 15 Pro | CellBroos",
    meta_description: "Xiaomi 15 Pro en uygun fiyatlarla CellBroos mağazasında.",
    category_id: "cat-3",
    category: { name: "Xiaomi", slug: "xiaomi" },
  },
  {
    id: "prod-4",
    name: "iPhone 16",
    slug: "iphone-16",
    description:
      "Apple iPhone 16 — A18 çip, Dynamic Island, 48MP kamera ve USB-C ile yeni nesil iPhone deneyimi.",
    brand: "Apple",
    model: "iPhone 16",
    price: 59999,
    specs: {
      ekran: '6.1" Super Retina XDR OLED',
      islemci: "A18",
      ram: "8 GB",
      depolama: "128 GB / 256 GB / 512 GB",
      kamera: "48MP + 12MP",
      pil: "3561 mAh",
      os: "iOS 18",
    },
    image_url: "/products/iphone-16.png",
    images: [],
    stock_status: "IN_STOCK",
    is_featured: false,
    is_active: true,
    display_order: 4,
    meta_title: "iPhone 16 | CellBroos",
    meta_description: "iPhone 16 en uygun fiyatlarla CellBroos mağazasında.",
    category_id: "cat-1",
    category: { name: "iPhone", slug: "iphone" },
  },
  {
    id: "prod-5",
    name: "Samsung Galaxy A56",
    slug: "samsung-galaxy-a56",
    description:
      "Orta segment şampiyonu. Güçlü kamera, uzun pil ömrü ve şık tasarımla fiyat/performans lideri.",
    brand: "Samsung",
    model: "Galaxy A56",
    price: 22999,
    specs: {
      ekran: '6.7" Super AMOLED',
      islemci: "Exynos 1580",
      ram: "8 GB",
      depolama: "128 GB / 256 GB",
      kamera: "50MP + 12MP + 5MP",
      pil: "5000 mAh",
      os: "Android 15 (One UI 7)",
    },
    image_url: "/products/samsung-galaxy-a56.png",
    images: [],
    stock_status: "OUT_OF_STOCK",
    is_featured: false,
    is_active: true,
    display_order: 5,
    meta_title: "Samsung Galaxy A56 | CellBroos",
    meta_description: "Samsung Galaxy A56 en uygun fiyatlarla CellBroos mağazasında.",
    category_id: "cat-2",
    category: { name: "Samsung", slug: "samsung" },
  },
  {
    id: "prod-6",
    name: "Xiaomi Redmi Note 14 Pro+",
    slug: "xiaomi-redmi-note-14-pro-plus",
    description:
      "Bütçe dostu performans canavarı. 200MP kamera, hızlı şarj ve büyük ekranla her şeyi yapın.",
    brand: "Xiaomi",
    model: "Redmi Note 14 Pro+",
    price: 16999,
    specs: {
      ekran: '6.67" AMOLED 120Hz',
      islemci: "Snapdragon 7s Gen 3",
      ram: "8 GB / 12 GB",
      depolama: "256 GB / 512 GB",
      kamera: "200MP + 8MP + 2MP",
      pil: "5110 mAh",
      os: "Android 14 (HyperOS)",
    },
    image_url: "/products/xiaomi-redmi-note-14-pro-plus.png",
    images: [],
    stock_status: "ON_ORDER",
    is_featured: false,
    is_active: true,
    display_order: 6,
    meta_title: "Xiaomi Redmi Note 14 Pro+ | CellBroos",
    meta_description: "Redmi Note 14 Pro+ en uygun fiyatlarla CellBroos mağazasında.",
    category_id: "cat-3",
    category: { name: "Xiaomi", slug: "xiaomi" },
  },

  // ─── KULAKLIKLAR ──────────────────────────────────────────────
  {
    id: "prod-7",
    name: "AirPods Pro (2. Nesil)",
    slug: "airpods-pro-2",
    description:
      "Aktif Gürültü Engelleme, Adaptif Ses ve MagSafe şarj kutusuyla Apple'ın en premium kablosuz kulaklığı.",
    brand: "Apple",
    model: "AirPods Pro 2",
    price: 9999,
    specs: {
      tip: "In-Ear TWS",
      gnc: "Aktif Gürültü Engelleme (ANC)",
      pil: "6 saat (kutuyla 30 saat)",
      baglanti: "Bluetooth 5.3",
      sarj: "MagSafe / Lightning / USB-C",
      su_direnci: "IPX4",
      mikrofon: "Adaptif Mikrofon Sistemi",
    },
    image_url: "/products/airpods-pro.png",
    images: [],
    stock_status: "IN_STOCK",
    is_featured: true,
    is_active: true,
    display_order: 7,
    meta_title: "AirPods Pro 2. Nesil | CellBroos",
    meta_description: "AirPods Pro 2. Nesil en uygun fiyatlarla CellBroos mağazasında.",
    category_id: "cat-4",
    category: { name: "Kulaklık", slug: "kulaklik" },
  },
  {
    id: "prod-8",
    name: "Samsung Galaxy Buds3 Pro",
    slug: "samsung-galaxy-buds3-pro",
    description:
      "Samsung'un üst segment TWS kulaklığı. Akıllı ANC, 360° ses ve ergonomik premium tasarım.",
    brand: "Samsung",
    model: "Galaxy Buds3 Pro",
    price: 6499,
    specs: {
      tip: "In-Ear TWS",
      gnc: "Aktif Gürültü Engelleme (ANC)",
      pil: "6 saat (kutuyla 26 saat)",
      baglanti: "Bluetooth 5.4",
      sarj: "USB-C / Kablosuz",
      su_direnci: "IPX7",
      mikrofon: "3 Mikrofon Dizisi",
    },
    image_url: "/products/samsung-galaxy-buds3-pro.png",
    images: [],
    stock_status: "IN_STOCK",
    is_featured: false,
    is_active: true,
    display_order: 8,
    meta_title: "Samsung Galaxy Buds3 Pro | CellBroos",
    meta_description: "Samsung Galaxy Buds3 Pro en uygun fiyatlarla CellBroos mağazasında.",
    category_id: "cat-4",
    category: { name: "Kulaklık", slug: "kulaklik" },
  },

  // ─── KILIF & KORUMA ───────────────────────────────────────────
  {
    id: "prod-9",
    name: "iPhone 16 Pro Max Şeffaf MagSafe Kılıf",
    slug: "iphone-clear-case-magsafe",
    description:
      "MagSafe destekli premium şeffaf kılıf. Telefonunuzun tasarımını korurken tam MagSafe şarj ve aksesuar uyumluluğu sağlar.",
    brand: "Apple",
    model: "iPhone 16 Pro Max Kılıf",
    price: 1299,
    specs: {
      uyumluluk: "iPhone 16 Pro Max",
      malzeme: "Optik Kalite Polikarbonat",
      magsafe: "Evet (15W)",
      koruma: "Dört Köşe Darbe Emici",
      agirlik: "42g",
      kalinlik: "1.2mm",
      renk: "Şeffaf",
    },
    image_url: "/products/iphone-clear-case-magsafe.png",
    images: [],
    stock_status: "IN_STOCK",
    is_featured: false,
    is_active: true,
    display_order: 9,
    meta_title: "iPhone 16 Pro Max Şeffaf MagSafe Kılıf | CellBroos",
    meta_description: "iPhone 16 Pro Max MagSafe kılıf CellBroos'ta.",
    category_id: "cat-5",
    category: { name: "Kılıf & Koruma", slug: "kilif" },
  },
  {
    id: "prod-10",
    name: "Samsung S25 Ultra Deri Cüzdan Kılıf",
    slug: "samsung-leather-case",
    description:
      "Premium deri görünümlü cüzdan kılıf. Kart bölmesi, manyetik kapak ve tam çerçeve koruması.",
    brand: "Samsung",
    model: "Galaxy S25 Ultra Kılıf",
    price: 899,
    specs: {
      uyumluluk: "Samsung Galaxy S25 Ultra",
      malzeme: "Premium PU Deri",
      kart_bolmesi: "2 Kart + Nakit",
      kapak: "Manyetik Kilit",
      koruma: "360° Tam Koruma",
      renk: "Lacivert / Siyah",
    },
    image_url: "/products/samsung-leather-case.png",
    images: [],
    stock_status: "IN_STOCK",
    is_featured: false,
    is_active: true,
    display_order: 10,
    meta_title: "Samsung S25 Ultra Deri Kılıf | CellBroos",
    meta_description: "Samsung Galaxy S25 Ultra deri cüzdan kılıf CellBroos'ta.",
    category_id: "cat-5",
    category: { name: "Kılıf & Koruma", slug: "kilif" },
  },
];
